import type { StickerAsset } from './media-catalog';

const sticker = (id: string, name: string, category: StickerAsset['category'], width: number, height: number): StickerAsset => ({
  id, name, category, width, height,
  src: `/stickers/wevi/${id.replace('.', '/')}.png`,
  keywords: ['wevi', 'thread', ...id.replace(/[._-]/g, ' ').split(' '), ...name.toLowerCase().split(' ')],
});

export const weviStickers: StickerAsset[] = [
  sticker("wevi_actions.idea", "Idea", "Wevi Actions", 308, 392),
  sticker("wevi_actions.wip", "WIP", "Wevi Actions", 321, 321),
  sticker("wevi_actions.done", "Done", "Wevi Actions", 336, 373),
  sticker("wevi_actions.wait", "Wait", "Wevi Actions", 306, 368),
  sticker("wevi_actions.yes", "Yes", "Wevi Actions", 287, 376),
  sticker("wevi_actions.nope", "Nope", "Wevi Actions", 303, 341),
  sticker("wevi_actions.fix-this", "Fix This", "Wevi Actions", 324, 372),
  sticker("wevi_actions.look-here", "Look Here", "Wevi Actions", 320, 376),
  sticker("wevi_actions.important", "Important", "Wevi Actions", 316, 337),
  sticker("wevi_actions.questions", "Questions", "Wevi Actions", 288, 341),
  sticker("wevi_actions.plus-one", "+1", "Wevi Actions", 287, 346),
  sticker("wevi_actions.lgtm", "LGTM", "Wevi Actions", 291, 343),
  sticker("wevi_actions.brainstorm", "Brainstorm", "Wevi Actions", 322, 335),
  sticker("wevi_actions.connect", "Connect", "Wevi Actions", 331, 345),
  sticker("wevi_actions.sketch", "Sketch", "Wevi Actions", 326, 350),
  sticker("wevi_actions.organize", "Organize", "Wevi Actions", 313, 338),
  sticker("wevi_moments.wave", "Wevi Wave", "Wevi Moments", 296, 301),
  sticker("wevi_moments.thinking", "Wevi Thinking", "Wevi Moments", 291, 330),
  sticker("wevi_moments.pencil", "Wevi Pencil", "Wevi Moments", 276, 315),
  sticker("wevi_moments.push-card", "Wevi Push Card", "Wevi Moments", 401, 301),
  sticker("wevi_moments.sticky-note", "Wevi Sticky Note", "Wevi Moments", 279, 312),
  sticker("wevi_moments.peek-note", "Wevi Peek Note", "Wevi Moments", 292, 308),
  sticker("wevi_moments.tangled", "Wevi Tangled", "Wevi Moments", 316, 343),
  sticker("wevi_moments.connect-nodes", "Wevi Connect Nodes", "Wevi Moments", 350, 267),
  sticker("wevi_moments.laptop", "Wevi Laptop", "Wevi Moments", 317, 281),
  sticker("wevi_moments.approved", "Wevi Approved", "Wevi Moments", 311, 300),
  sticker("wevi_moments.sleep", "Wevi Sleep", "Wevi Moments", 316, 329),
  sticker("wevi_moments.pull-nodes", "Wevi Pull Nodes", "Wevi Moments", 338, 263),
  sticker("wevi_moments.thread-loop", "Thread Loop", "Wevi Moments", 320, 268),
  sticker("wevi_moments.knot", "Thread Knot", "Wevi Moments", 298, 238),
  sticker("wevi_moments.spool", "Thread Spool", "Wevi Moments", 321, 296),
  sticker("wevi_moments.thread-wordmark", "Thread Wordmark", "Wevi Moments", 368, 187),
  sticker("canvas_ui.cursor", "Cursor", "Canvas Icons", 220, 282),
  sticker("canvas_ui.move", "Move", "Canvas Icons", 277, 278),
  sticker("canvas_ui.resize", "Resize", "Canvas Icons", 278, 285),
  sticker("canvas_ui.connector", "Connector", "Canvas Icons", 347, 255),
  sticker("canvas_ui.wevi-card", "Wevi Card", "Canvas Icons", 410, 301),
  sticker("canvas_ui.note", "Note", "Canvas Icons", 306, 272),
  sticker("canvas_ui.pinned-note", "Pinned Note", "Canvas Icons", 306, 349),
  sticker("canvas_ui.folded-page", "Folded Page", "Canvas Icons", 273, 285),
  sticker("canvas_ui.arrow", "Arrow", "Canvas Icons", 335, 233),
  sticker("canvas_ui.circle", "Hand-drawn Circle", "Canvas Icons", 306, 262),
  sticker("canvas_ui.underline", "Underline", "Canvas Icons", 351, 276),
  sticker("canvas_ui.tape", "Tape", "Canvas Icons", 302, 260),
  sticker("canvas_ui.selection-box", "Selection Box", "Canvas Icons", 318, 261),
  sticker("canvas_ui.add", "Add", "Canvas Icons", 233, 279),
  sticker("canvas_ui.card-stack", "Card Stack", "Canvas Icons", 343, 293),
  sticker("canvas_ui.comment", "Comment", "Canvas Icons", 276, 275),
  sticker("canvas_ui.pin-card", "Wevi Pin Card", "Canvas Icons", 541, 326),
  sticker("canvas_ui.present-card", "Wevi Present Card", "Canvas Icons", 468, 325),
  sticker("thread_workflow.laptop", "Wevi Laptop", "Workflow", 341, 291),
  sticker("thread_workflow.idea", "Think / Idea", "Workflow", 261, 399),
  sticker("thread_workflow.node-map", "Node Map", "Workflow", 356, 334),
  sticker("thread_workflow.cards", "Card Stack", "Workflow", 355, 311),
  sticker("thread_workflow.start-here", "Start Here", "Workflow", 318, 318),
  sticker("thread_workflow.checklist", "Checklist", "Workflow", 303, 297),
  sticker("thread_workflow.connections", "Connections", "Workflow", 326, 321),
  sticker("thread_workflow.carry-card", "Carry Card", "Workflow", 353, 330),
  sticker("thread_workflow.board-done", "Board Done", "Workflow", 413, 361),
  sticker("thread_workflow.brain-dump", "Brain Dump", "Workflow", 306, 343),
  sticker("thread_workflow.network", "Network", "Workflow", 306, 329),
  sticker("thread_workflow.stack", "Stack", "Workflow", 300, 297),
  sticker("thread_workflow.start-arrow", "Start Arrow", "Workflow", 347, 228),
  sticker("thread_workflow.focus-mode", "Focus Mode", "Workflow", 336, 326),
  sticker("thread_workflow.tangle-to-flow", "Tangle to Flow", "Workflow", 326, 183),
  sticker("thread_workflow.ship-it", "Ship It", "Workflow", 316, 317),
];
