import type { StickerAsset } from './media-catalog';

const sticker = (id: string, name: string, category: StickerAsset['category'], width: number, height: number): StickerAsset => ({
  id, name, category, width, height,
  src: `/stickers/wevi/${id.replace('.', '/')}.png`,
  keywords: ['wevi', 'thread', ...id.replace(/[._-]/g, ' ').split(' '), ...name.toLowerCase().split(' ')],
});

export const weviStickers: StickerAsset[] = [
  sticker("wevi_actions.idea", "Idea", "Wevi Actions", 297, 382),
  sticker("wevi_actions.wip", "WIP", "Wevi Actions", 300, 300),
  sticker("wevi_actions.done", "Done", "Wevi Actions", 316, 365),
  sticker("wevi_actions.wait", "Wait", "Wevi Actions", 268, 359),
  sticker("wevi_actions.yes", "Yes", "Wevi Actions", 275, 344),
  sticker("wevi_actions.nope", "Nope", "Wevi Actions", 282, 331),
  sticker("wevi_actions.fix-this", "Fix This", "Wevi Actions", 301, 332),
  sticker("wevi_actions.look-here", "Look Here", "Wevi Actions", 290, 337),
  sticker("wevi_actions.important", "Important", "Wevi Actions", 304, 315),
  sticker("wevi_actions.questions", "Questions", "Wevi Actions", 244, 317),
  sticker("wevi_actions.plus-one", "+1", "Wevi Actions", 276, 304),
  sticker("wevi_actions.lgtm", "LGTM", "Wevi Actions", 280, 316),
  sticker("wevi_actions.brainstorm", "Brainstorm", "Wevi Actions", 308, 306),
  sticker("wevi_actions.connect", "Connect", "Wevi Actions", 317, 274),
  sticker("wevi_actions.sketch", "Sketch", "Wevi Actions", 282, 328),
  sticker("wevi_actions.organize", "Organize", "Wevi Actions", 286, 298),
  sticker("wevi_moments.wave", "Wevi Wave", "Wevi Moments", 282, 287),
  sticker("wevi_moments.thinking", "Wevi Thinking", "Wevi Moments", 256, 317),
  sticker("wevi_moments.pencil", "Wevi Pencil", "Wevi Moments", 243, 286),
  sticker("wevi_moments.push-card", "Wevi Push Card", "Wevi Moments", 369, 263),
  sticker("wevi_moments.sticky-note", "Wevi Sticky Note", "Wevi Moments", 265, 298),
  sticker("wevi_moments.peek-note", "Wevi Peek Note", "Wevi Moments", 278, 293),
  sticker("wevi_moments.tangled", "Wevi Tangled", "Wevi Moments", 257, 329),
  sticker("wevi_moments.connect-nodes", "Wevi Connect Nodes", "Wevi Moments", 337, 253),
  sticker("wevi_moments.laptop", "Wevi Laptop", "Wevi Moments", 303, 266),
  sticker("wevi_moments.approved", "Wevi Approved", "Wevi Moments", 287, 285),
  sticker("wevi_moments.sleep", "Wevi Sleep", "Wevi Moments", 304, 291),
  sticker("wevi_moments.pull-nodes", "Wevi Pull Nodes", "Wevi Moments", 325, 250),
  sticker("wevi_moments.thread-loop", "Thread Loop", "Wevi Moments", 306, 254),
  sticker("wevi_moments.knot", "Thread Knot", "Wevi Moments", 269, 213),
  sticker("wevi_moments.spool", "Thread Spool", "Wevi Moments", 243, 236),
  sticker("wevi_moments.thread-wordmark", "Thread Wordmark", "Wevi Moments", 356, 172),
  sticker("canvas_ui.cursor", "Cursor", "Canvas Icons", 210, 272),
  sticker("canvas_ui.move", "Move", "Canvas Icons", 266, 269),
  sticker("canvas_ui.resize", "Resize", "Canvas Icons", 268, 274),
  sticker("canvas_ui.connector", "Connector", "Canvas Icons", 311, 244),
  sticker("canvas_ui.wevi-card", "Wevi Card", "Canvas Icons", 388, 290),
  sticker("canvas_ui.note", "Note", "Canvas Icons", 262, 246),
  sticker("canvas_ui.pinned-note", "Pinned Note", "Canvas Icons", 263, 315),
  sticker("canvas_ui.folded-page", "Folded Page", "Canvas Icons", 236, 275),
  sticker("canvas_ui.arrow", "Arrow", "Canvas Icons", 317, 190),
  sticker("canvas_ui.circle", "Hand-drawn Circle", "Canvas Icons", 282, 225),
  sticker("canvas_ui.underline", "Underline", "Canvas Icons", 269, 159),
  sticker("canvas_ui.tape", "Tape", "Canvas Icons", 291, 192),
  sticker("canvas_ui.selection-box", "Selection Box", "Canvas Icons", 296, 232),
  sticker("canvas_ui.add", "Add", "Canvas Icons", 223, 220),
  sticker("canvas_ui.card-stack", "Card Stack", "Canvas Icons", 332, 258),
  sticker("canvas_ui.comment", "Comment", "Canvas Icons", 239, 216),
  sticker("canvas_ui.pin-card", "Wevi Pin Card", "Canvas Icons", 506, 294),
  sticker("canvas_ui.present-card", "Wevi Present Card", "Canvas Icons", 444, 275),
  sticker("thread_workflow.laptop", "Wevi Laptop", "Workflow", 314, 280),
  sticker("thread_workflow.idea", "Think / Idea", "Workflow", 236, 386),
  sticker("thread_workflow.node-map", "Node Map", "Workflow", 342, 324),
  sticker("thread_workflow.cards", "Card Stack", "Workflow", 316, 297),
  sticker("thread_workflow.start-here", "Start Here", "Workflow", 307, 306),
  sticker("thread_workflow.checklist", "Checklist", "Workflow", 270, 285),
  sticker("thread_workflow.connections", "Connections", "Workflow", 291, 309),
  sticker("thread_workflow.carry-card", "Carry Card", "Workflow", 317, 267),
  sticker("thread_workflow.board-done", "Board Done", "Workflow", 400, 325),
  sticker("thread_workflow.brain-dump", "Brain Dump", "Workflow", 272, 293),
  sticker("thread_workflow.network", "Network", "Workflow", 268, 272),
  sticker("thread_workflow.stack", "Stack", "Workflow", 257, 247),
  sticker("thread_workflow.start-arrow", "Start Arrow", "Workflow", 331, 218),
  sticker("thread_workflow.focus-mode", "Focus Mode", "Workflow", 274, 280),
  sticker("thread_workflow.tangle-to-flow", "Tangle to Flow", "Workflow", 288, 172),
  sticker("thread_workflow.ship-it", "Ship It", "Workflow", 276, 307),
];
